Models/Book.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace MyBookClub.Models
{
    public class Book
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [DisplayName("Release Year")]
        [Range(1, 2022, ErrorMessage = "Display order must be between numbers 1 & 2022")]
        public int ReleaseYear { get; set; }
       
    }
}

Controllers/BookController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyBookClub.Areas.Identity.Data;
using MyBookClub.Models;

namespace MyBookClub.Controllers
{
    [Authorize]
    public class BookController : Controller
    {
        private readonly AuthorizationDbContext _db;
        public BookController(AuthorizationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<Book> objCategoryList = _db.Books;
            return View(objCategoryList);
        }
        //Get
        public IActionResult Create()
        {
            return View();
        }
        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Book obj)
        {
            if (obj.Name == obj.ReleaseYear.ToString())
            {
                ModelState.AddModelError("name", "ReleaseYear Cannot exactly match the Name.");
            }
            if (ModelState.IsValid)
            {
                _db.Books.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }
        //Get
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var categoryFromDb = _db.Books.Find(id);
            //var categoryFromDbFirst=_db.Categories.FirstOrDefault(u=>u.Id==id);
            //var categoryFromDbSingle = _db.Categories.SingleOrDefault(u=>u.Id==id);
            if (categoryFromDb == null)
            {
                return NotFound();
            }
            return View(categoryFromDb);
        }
        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Book obj)
        {
            if (obj.Name == obj.ReleaseYear.ToString())
            {
                ModelState.AddModelError("name", "ReleaseYear Cannot exactly match the Name.");
            }
            if (ModelState.IsValid)
            {
                _db.Books.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }
        //Get
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var categoryFromDb = _db.Books.Find(id);
            //var categoryFromDbFirst=_db.Categories.FirstOrDefault(u=>u.Id==id);
            //var categoryFromDbSingle = _db.Categories.SingleOrDefault(u=>u.Id==id);
            if (categoryFromDb == null)
            {
                return NotFound();
            }
            return View(categoryFromDb);
        }
        //Post
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var obj = _db.Books.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            _db.Books.Remove(obj);
            _db.SaveChanges();
            TempData["success"] = "Category Deleted successfully";
            return RedirectToAction("Index");

        }
    }
}

Views/Book/Create.cshtml
@model Book

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary"> Create Book</h2>
            <hr />
        </div>
      @*  <div asp-validation-summary="All"></div>*@
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control"/>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="ReleaseYear"></label>
            <input asp-for="ReleaseYear" class="form-control"/>
             <span asp-validation-for="ReleaseYear" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
        <a asp-controller="Book" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to list
        </a>
    </div>
</form>
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Views/Book/Delete.cshtml
@model Book

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary"> Delete Book</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" disabled class="form-control"/>
        </div>
        <div class="mb-3">
            <label asp-for="ReleaseYear"></label>
            <input asp-for="ReleaseYear" disabled class="form-control"/>
        </div>
        <button type="submit" class="btn btn-danger" style="width:150px">Delete</button>
        <a asp-controller="Book" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to list
        </a>
    </div>
</form>

Views/Book/Edit.cshtml
@model Book

<form method="post" asp-action="Edit">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary"> Edit Book</h2>
            <hr />
        </div>
      @*  <div asp-validation-summary="All"></div>*@
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control"/>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="ReleaseYear"></label>
            <input asp-for="ReleaseYear" class="form-control"/>
             <span asp-validation-for="ReleaseYear" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Update</button>
        <a asp-controller="Book" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to list
        </a>
    </div>
</form>
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Views/Book/Index.cshtml
@model IEnumerable<Book>
@{
    ViewData["Title"] = "Index";
}


<div class="container p-3"> 

    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Book List</h2>
        </div>
     
        <div class="col-6 text-end">
            <a asp-controller="Book" asp-action="Create" class="btn btn-primary"> 
               <i class="bi bi-plus-circle"></i> &nbsp; Create New Book
            </a>
        </div>
    </div>
    <br /><br />


<table class="table table-boarded table-striped" style="width:100%">
    <thead>
        <tr>
            <th>
                Book Name
            </th>
            <th>
                Release Year
            </th>
            <th></th>
        </tr>
    </thead>
    
    <tbody>
        @foreach(var obj in Model)
        {
            
            <tr>
                <td width="50%">
                    @obj.Name
                </td>
                <td width="30%">
                    @obj.ReleaseYear
                    
                </td>
                <td>
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="Book" asp-action="Edit" asp-route-id="@obj.Id"
                        class="btn btn-primary mx-2"><i class="bi bi-pencil-square"> </i>Edit</a>
                         <a asp-controller="Book" asp-action="Delete" asp-route-id="@obj.Id"
                        class="btn btn-danger mx-2"> <i class="bi bi-trash-fill"></i>Delete</a>
                    </div>
                </td>

            </tr>
        }
    </tbody>
</table>
</div>